name: 'sql_to_dbt_guide'

config-version: 2
version: '0.1'

profile: 'sql_to_dbt_guide'

model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]
snapshot-paths: ["snapshots"]
analysis-paths: ["analysis"]
macro-paths: ["macros"]

models:
  sql_to_dbt_guide:
    staging:
      +materialized: table
      +schema: staging
      #+contract: # Comment these 2 lines to disable contract validation
      #  enforced: true 
    intermediate:
      +materialized: view
      +schema: intermediate
    marts:
      +materialized: view
      +schema: marts
    ephemeral:
      +materialized: ephemeral

target-path: "target"
clean-targets:
    - "target"
    - "dbt_modules"
    - "logs"

require-dbt-version: [">=1.0.0", "<2.0.0"]

flags:
  require_generic_test_arguments_property: true
