version: 2

models:
  - name: campaign_performance
    description: "Campaign-level performance aggregation with spend, conversions, and ROAS metrics"
    columns:
      - name: campaign_id
        data_tests:
          - unique
          - not_null
        description: "Unique campaign identifier"
      - name: campaign_name
        data_tests:
          - not_null
        description: "Campaign name"
      - name: campaign_channel
        data_tests:
          - accepted_values:
              arguments:
                values: ["social", "search", "display", "email", "referral"]
        description: "Campaign marketing channel"
      - name: total_impressions
        data_tests:
          - not_null
        description: "Total ad impressions across all ads in campaign"
      - name: total_clicks
        data_tests:
          - not_null
        description: "Total ad clicks across all ads in campaign"
      - name: total_ad_spend
        data_tests:
          - not_null
        description: "Total spend across all ads in campaign"
      - name: total_conversions
        data_tests:
          - not_null
        description: "Total conversions attributed to campaign"
      - name: total_revenue
        data_tests:
          - not_null
        description: "Total revenue attributed to campaign"
      - name: roas
        description: "Return on ad spend (revenue / spend)"
      - name: conversion_rate_pct
        description: "Conversion rate as percentage of sessions"
      - name: actual_cpa
        description: "Actual cost per acquisition"
      - name: revenue_per_visitor
        description: "Average revenue generated per visitor"

  - name: conversion_attribution
    description: "Multi-touch attribution analysis for conversions with first/last touch data"
    columns:
      - name: conversion_id
        data_tests:
          - unique
          - not_null
        description: "Unique conversion identifier"
      - name: visitor_id
        data_tests:
          - not_null
        description: "Visitor who converted"
      - name: conversion_type
        data_tests:
          - accepted_values:
              arguments:
                values: ["purchase", "lead", "signup", "appointment", "download"]
        description: "Type of conversion"
      - name: conversion_value
        data_tests:
          - not_null
        description: "Monetary value of the conversion"
      - name: first_touch_channel
        description: "Channel of first touchpoint in customer journey"
      - name: first_touch_campaign
        description: "Campaign of first touchpoint in customer journey"
      - name: last_touch_channel
        description: "Channel of last touchpoint before conversion"
      - name: last_touch_campaign
        description: "Campaign of last touchpoint before conversion"
      - name: total_touchpoints
        description: "Total number of touchpoints in conversion journey"
      - name: journey_length_days
        description: "Length of customer journey in days"
      - name: is_first_touch_conversion
        data_tests:
          - not_null
        description: "Flag indicating if conversion attributed to first touch"
      - name: is_last_touch_conversion
        data_tests:
          - not_null
        description: "Flag indicating if conversion attributed to last touch"

  - name: visitor_journey
    description: "Visitor-level journey aggregation with engagement metrics and segmentation"
    columns:
      - name: visitor_id
        data_tests:
          - unique
          - not_null
        description: "Unique visitor identifier"
      - name: total_sessions
        data_tests:
          - not_null
        description: "Total number of sessions for visitor"
      - name: total_conversions
        data_tests:
          - not_null
        description: "Total conversions by visitor"
      - name: total_revenue
        data_tests:
          - not_null
        description: "Total revenue generated by visitor"
      - name: journey_span_days
        description: "Length of visitor journey from first to last session"
      - name: first_source_medium
        description: "Source/medium of visitor's first session"
      - name: first_campaign
        description: "Campaign of visitor's first session"
      - name: last_source_medium
        description: "Source/medium of visitor's last session"
      - name: last_campaign
        description: "Campaign of visitor's last session"
      - name: visitor_frequency_segment
        data_tests:
          - accepted_values:
              arguments:
                values: ["single_session", "low_frequency", "medium_frequency", "high_frequency"]
        description: "Visitor segmentation based on session frequency"
      - name: visitor_value_segment
        data_tests:
          - accepted_values:
              arguments:
                values: ["non_converter", "low_value", "medium_value", "high_value"]
        description: "Visitor segmentation based on revenue generated"
      - name: visitor_engagement_segment
        data_tests:
          - accepted_values:
              arguments:
                values: ["low_engagement", "medium_engagement", "high_engagement"]
        description: "Visitor segmentation based on average time on site"
      - name: session_conversion_rate_pct
        description: "Percentage of sessions that resulted in conversion"
      - name: revenue_per_session
        description: "Average revenue generated per session"
      - name: revenue_per_minute
        description: "Revenue generated per minute spent on site"