version: 2

models:
  - name: stg_campaigns
    description: Marketing campaigns from synthetic data
    columns:
      - name: campaign_id
        data_type: string
        constraints:
          - type: not_null
          - type: primary_key
          - type: unique
        data_tests:
          - uuid_format
          - dbt_expectations.expect_column_values_to_match_regex:
              arguments:
                regex: '^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$'
        description: Unique identifier for a campaign
      - name: campaign_name
        data_type: string
        data_tests:
          - not_null
        description: Name of the campaign
      - name: channel
        data_type: string
        data_tests:
          - accepted_values:
              arguments:
                values: ["social", "search", "display", "email", "referral"]
        description: Marketing channel
      - name: start_date
        data_type: varchar
        data_tests:
          - not_null
        description: Campaign start date
      - name: end_date
        data_type: varchar
        description: Campaign end date
      - name: lifetime_spend
        data_type: double
        description: Total lifetime spend for campaign
      - name: total_revenue
        data_type: double
        description: Total revenue generated by campaign
      - name: roi
        data_type: double
        constraints:
          - type: check
            expression: "roi >= -1"
            name: "roi_reasonable_range"
        description: Return on investment
      - name: target_cpa
        data_type: double
        constraints:
          - type: check
            expression: "target_cpa > 0"
        description: Target cost per acquisition
      - name: status
        data_type: varchar
        description: Campaign status
      - name: objective
        data_type: varchar
        description: Campaign objective
      - name: campaign_manager
        data_type: varchar
        description: Campaign manager name
      - name: created_at
        data_type: varchar
        description: Campaign creation timestamp
      - name: notes
        data_type: varchar
        description: Campaign notes
      - name: budget
        data_type: double
        constraints:
          - type: not_null
          - type: check
            expression: "budget > 0"
          - type: check
            expression: "budget >= 1000"
            name: "budget_minimum_threshold"
        data_tests:
          - positive_numeric
          - dbt_expectations.expect_column_values_to_be_between:
              arguments:
                min_value: 1000
                max_value: 10000000
        description: Campaign budget amount

  - name: stg_ads
    description: Ad performance data from synthetic data
    columns:
      - name: ad_id
        data_type: string
        constraints:
          - type: not_null
        data_tests:
          - uuid_format
        description: Unique identifier for an ad
      - name: campaign_id
        data_type: string
        constraints:
          - type: not_null
        data_tests:
          - uuid_format
          - relationships:
              arguments:
                to: ref('stg_campaigns')
                field: campaign_id
        description: Campaign this ad belongs to
      - name: impressions
        data_type: double
        data_tests:
          - positive_numeric
        description: Number of ad impressions
      - name: clicks
        data_type: double
        data_tests:
          - positive_numeric
        description: Number of ad clicks
      - name: ctr
        data_type: double
        constraints:
          - type: check
            expression: "ctr >= 0 AND ctr <= 1"
            name: "ctr_valid_percentage"
        data_tests:
          - percentage_bounds
          - dbt_expectations.expect_column_values_to_be_between:
              arguments:
                min_value: 0
                max_value: 1
        description: Click-through rate
      - name: spend
        data_type: double
        constraints:
          - type: check
            expression: "spend >= 0"
        data_tests:
          - positive_numeric
        description: Ad spend amount
      - name: ad_name
        data_type: varchar
        description: Name of the ad
      - name: creative_type
        data_type: varchar
        description: Type of creative used
      - name: platform
        data_type: varchar
        description: Advertising platform
      - name: placement
        data_type: varchar
        description: Ad placement
      - name: avg_cpc
        data_type: double
        constraints:
          - type: check
            expression: "avg_cpc >= 0"
        description: Average cost per click
      - name: conversions
        data_type: double
        description: Number of conversions
      - name: start_date
        data_type: varchar
        description: Ad start date
      - name: end_date
        data_type: varchar
        description: Ad end date
      - name: ad_status
        data_type: varchar
        description: Ad status
      - name: cpa
        data_type: double
        constraints:
          - type: check
            expression: "cpa >= 0"
        description: Cost per acquisition
      - name: last_updated
        data_type: varchar
        description: Last updated timestamp
      - name: targeting
        data_type: varchar
        description: Ad targeting criteria

  - name: stg_sessions
    description: Website sessions from synthetic data
    columns:
      - name: session_id
        data_type: string
        constraints:
          - type: not_null
          - type: primary_key
          - type: unique
        data_tests:
          - uuid_format
        description: Unique identifier for a session
      - name: visitor_id
        data_type: string
        constraints:
          - type: not_null
        data_tests:
          - not_null
          - uuid_format
        description: Unique identifier for a visitor
      - name: campaign_id
        data_type: string
        data_tests:
          - uuid_format
          - relationships:
              arguments:
                to: ref('campaigns')
                field: campaign_id
        description: Campaign associated with session
      - name: ad_id
        data_type: varchar
        description: Ad associated with session
      - name: source_medium
        data_type: varchar
        description: Traffic source and medium
      - name: landing_page
        data_type: varchar
        description: Landing page URL
      - name: session_start
        data_type: varchar
        description: Session start time
      - name: session_end
        data_type: varchar
        description: Session end time
      - name: pages_viewed
        data_type: double
        description: Number of pages viewed in session
      - name: bounce
        data_type: boolean
        description: Whether session was a bounce
      - name: time_on_site_seconds
        data_type: double
        description: Time spent on site in seconds
      - name: events_count
        data_type: double
        description: Number of events in session
      - name: conversion_flag
        data_type: boolean
        description: Whether session resulted in conversion

  - name: stg_conversions
    description: Conversion events from synthetic data
    columns:
      - name: conversion_id
        data_type: string
        constraints:
          - type: not_null
          - type: primary_key
          - type: unique
        data_tests:
          - uuid_format
        description: Unique identifier for a conversion
      - name: session_id
        data_type: string
        constraints:
          - type: not_null
        data_tests:
          - uuid_format
          - relationships:
              arguments:
                to: ref('stg_sessions')
                field: session_id
        description: Session where conversion occurred
      - name: conversion_value
        data_type: double
        constraints:
          - type: check
            expression: "conversion_value >= 0"
        data_tests:
          - positive_numeric
        description: Monetary value of the conversion
      - name: conversion_type
        data_type: string
        constraints:
          - type: not_null
        data_tests:
          - accepted_values:
              arguments:
                values: ["purchase", "lead", "signup", "appointment", "download"]
        description: Type of conversion event
      - name: visitor_id
        data_type: varchar
        description: Visitor who made the conversion
      - name: campaign_id
        data_type: varchar
        description: Campaign associated with conversion
      - name: ad_id
        data_type: varchar
        description: Ad associated with conversion
      - name: conversion_time
        data_type: varchar
        description: Time of conversion
      - name: revenue
        data_type: double
        constraints:
          - type: check
            expression: "revenue >= 0"
        description: Revenue from conversion
      - name: attribution_model
        data_type: varchar
        description: Attribution model used
      - name: attributed_spend
        data_type: double
        constraints:
          - type: check
            expression: "attributed_spend >= 0"
        description: Attributed spend for conversion
      - name: cpa
        data_type: double
        constraints:
          - type: check
            expression: "cpa >= 0"
        description: Cost per acquisition
      - name: conversion_channel
        data_type: varchar
        description: Channel where conversion occurred
      - name: is_revenue_confirmed
        data_type: boolean
        description: Whether revenue is confirmed
      - name: order_id
        data_type: varchar
        description: Order identifier

  - name: stg_journey_events
    description: Customer journey events from synthetic data
    columns:
      - name: event_id
        data_type: string
        constraints:
          - type: not_null
          - type: primary_key
          - type: unique
        data_tests:
          - uuid_format
        description: Unique identifier for an event
      - name: visitor_id
        data_type: string
        constraints:
          - type: not_null
        data_tests:
          - not_null
          - uuid_format
        description: Visitor who performed the event
      - name: session_id
        data_type: string
        data_tests:
          - uuid_format
          - relationships:
              arguments:
                to: ref('sessions')
                field: session_id
        description: Session where event occurred
      - name: campaign_id
        data_type: string
        data_tests:
          - uuid_format
          - relationships:
              arguments:
                to: ref('campaigns')
                field: campaign_id
        description: Campaign associated with event
      - name: ad_id
        data_type: string
        data_tests:
          - uuid_format
          - relationships:
              arguments:
                to: ref('ads')
                field: ad_id
        description: Ad associated with event
      - name: event_type
        data_type: string
        constraints:
          - type: not_null
        data_tests:
          - accepted_values:
              arguments:
                values: ["page_view", "click", "purchase", "conversion", "lead", "signup", "call"]
        description: Type of journey event
      - name: timestamp
        data_type: varchar
        constraints:
          - type: not_null
        data_tests:
          - not_null
        description: Event timestamp
      - name: channel
        data_type: varchar
        description: Marketing channel
      - name: page_url
        data_type: varchar
        description: Page URL where event occurred
      - name: event_value
        data_type: double
        description: Value associated with the event
      - name: touchpoint_order
        data_type: double
        description: Order of touchpoint in journey

# Table-level dbt-expectations tests
tests:
  - dbt_expectations.expect_table_row_count_to_be_between:
      name: test_campaigns_row_count
      model: ref('campaigns')
      arguments:
        min_value: 100
        max_value: 50000
      
  - dbt_expectations.expect_table_row_count_to_be_between:
      name: test_sessions_row_count  
      model: ref('sessions')
      arguments:
        min_value: 1000
        max_value: 100000

  - dbt_expectations.expect_table_aggregation_to_equal_other_table:
      name: test_ads_campaigns_referential_integrity
      model: ref('ads')
      arguments:
        expression: count(distinct campaign_id)
        compare_model: ref('campaigns')
        compare_expression: count(distinct campaign_id)
        tolerance: 0.1